services:
  homer_www:
    image: pknw1/homer_www:latest
    container_name: homer_www
    hostname: homer_www
    networks:
      - proxy
    environment:
      - VIRTUAL_HOST=homer_www.pknw1.co.uk
      - VIRTUAL_PORT=80
      - APP_GROUP=Content
      - APP_LOGO=https://static-00.iconduck.com/assets.00/portainer-icon-1465x2048-t155ekm0.png
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 200M

networks:
  proxy:
    external: true
