---
# Homepage configuration
# See https://fontawesome.com/search for icons options
title: "PKNW1"
subtitle: "www"
documentTitle: "www.pknw1.co.uk" # Customize the browser tab text
logo: "assets/images/pknw1-logo-128x77.png"
header: false # Set to false to hide the header
footer: 'pknw1'
columns: "2" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: false # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).
defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: dark 
    #stylesheet:
    #  - "/assets/style.css"
theme: default # 'default' or one of the themes available in 'src/assets/themes'.
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#424242"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
    background-image: "/assets/your/light/bg.png" # prefix with your sub subpath if any (ex: /homer/assets/...)
  dark:
    highlight-primary: "#232323"
    highlight-secondary: "#e5a00d"
    highlight-hover: "#232323"
    background: "#232323" #"#131313"
    card-background: "#2b2b2b"
    text: "#e5a00d"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#e5a00d"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#e5a00d"
    link-hover: "#ff0000"
    background-image: "/assets/your/dark/bg.png" # prefix with your sub subpath if any (ex: /homer/assets/...)

message:
  title: PKNW1
  style: "is-warning"
  background-image: "https://www.pknw1.co.uk/assets/images/icon-128x77.png"
  icon: "fa fa-exclamation-triangle"
  content:
    <style>@import "/assets/css/index.css";</style>
        <div class="before-message">
          <a href="#" class="button">Link Button</a>
      <a href="https://www.pkn1.co.uk">
        <img src="https://www.pknw1.co.uk/assets/images/icon-128x77.png?h=220"/>
      </a>
    </div>

    <iframe src="https://www.pknw1.co.uk" scrolling="none"></iframe>
    <div>
    <iframe src="https://www.pknw1.co.uk" scrolling="none"></iframe>

    <div class="after-message">
      <a href="#" class="button">Link Button</a>
      <a href="https://www.pkn1.co.uk">
        <img src="https://www.pknw1.co.uk/assets/images/icon-128x77.png?h=220"/>
      </a>
    </div>
    </div>
  # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
  # mapping: # allows to map fields from the remote format to the one expected by Homer
  #   title: 'id' # use value from field 'id' as title
  #   content: 'value' # value from field 'value' as content
  # refreshInterval: 10000 # Optional: time interval to refresh message
  #
  # Real example using chucknorris.io for showing Chuck Norris facts as messages:
  # url: https://api.chucknorris.io/jokes/random
  # mapping:
  #   title: 'id'
  #   content: 'value'
  # refreshInterval: 10000
  #style: "is-error"
  #title: "Optional message!"
  #icon: "fa fa-exclamation-triangle"
  # The content also accepts HTML content, so you can add divs, images or whatever you want to make match your needs.
  #content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: ""
    icon: "fa-solid fa-rocket"
    url: "#"
  - name: ""
    icon: "fa-solid fa-unlock"
    url: "#users"
  - name: ""
    icon: "fa-solid fa-lock"
    url: "https://admin.pknw1.co.uk"
  - name: ""
    icon: "fa-solid fa-address-book"
    url: "#contact"
  - name: ""
    icon: "fa-solid fa-code"
    url: "#dev"
  - name: ""
    icon: "fa-solid fa-laptop-file"
    url: "#professional"
  - name: ""
    icon: "fa-solid fa-film"
    url: "#notflix"

